[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./"}]
solc = "0.8.21"
verbosity = 2

optimizer = true
optimizer_runs = 999_999
via_ir=true

# If we ever want to customize the IR optimizer:
# [profile.default.optimizer_details.yulDetails]
# optimizerSteps = ""

# See more config options https://book.getfoundry.sh/reference/config/
